### PR TITLE
2.3.0 dev virtual keyboard

### PR DESCRIPTION
**Pull request by connor-makowski**

### CODE REVIEW

**Comment by luisvasq** [comment]
@brianzheng205, @connor-makowski: I pushed some minor styling updates and took an opinionated approach to separate `shift` from `caps` behavior. Essentially, `shift` will enable uppercase letters and provide access to special characters, while `caps` will only enable uppercase letters. I tried to emulate the conventional keyboard behavior when combining `shift` with `caps`.

Brian, great job with this super useful feature! If you notice anything off after my changes, feel free to fix it if you have time. Otherwise, I'd fix any potential bug(s) on Friday. I'll merge soon...

**Comment by luisvasq** [comment]
I quickly resolved the conflicts before the merge and realized that the fix for #530 is broken for virtual keyboard input. @brianzheng205: since you worked on that issue, could you check it out? Lmk if I can help with anything.

**Comment by brianzheng205** [comment]
@luisvasq Sure! I'll look into it.

**Comment by brianzheng205** [comment]
@luisvasq Bug should be fixed.

**Comment by luisvasq** [comment]
@brianzheng205, nice fix. :100: We're ready to merge.

**Review by luisvasq — APPROVED** [review]

**Pull request merged**
