### PR TITLE
Marquee scroll fix

### PR DESCRIPTION
**Pull request by ayang0675**
marquee scrolls only when units don't fit in the box.

### CODE REVIEW

**Comment by connor-makowski** [comment]
@luisvasq can you check this out and merge if it makes sense to you?

**Comment by luisvasq** [comment]
This will be a useful fix. While looking into this, I noticed that some marquee-ing values, as shown below, may disappear when the `OverflowText` component is initially mounted.

no-value-in-marquee

**Comment by luisvasq** [comment]
@ayang0675, let me know if I can help with anything here!

**Comment by ayang0675** [comment]
@luisvasq Thanks so much for catching that. How do i get to this screen?

**Comment by luisvasq** [comment]
> @luisvasq Thanks so much for catching that. How do i get to this screen?

Of course. While on the first dashboard page of the `kitchen_sink` example, click on the reset button and you should see the values ​​disappear.

**Comment by ayang0675** [comment]
> > @luisvasq Thanks so much for catching that. How do i get to this screen?
> 
> Of course. While on the first dashboard page of the `kitchen_sink` example, click on the reset button and you should see the values ​​disappear.

i think the issue is fixed now

**Comment by connor-makowski** [comment]
@luisvasq can you verify this and merge if everything checks out.

**Comment by luisvasq** [comment]
> @luisvasq can you verify this and merge if everything checks out.

LGTM! Nice job, @ayang0675. Merging now.

**Pull request merged**
