### PR TITLE
Support Multi Step Selector Slider

### PR DESCRIPTION
**Pull request by maxtkc**
Implement `hradio`, `vstepper`, and `hstepper` variants of `selector`.

Example:

image

Solves #230

### CODE REVIEW

**Comment by connor-makowski** [comment]
@maxtkc Can you remove the vertical gray line on the right hand side of the component?

**Comment by connor-makowski** [comment]
All three

**Comment by maxtkc** [comment]
image

With no dividers

**Comment by connor-makowski** [comment]
Okay, lets go ahead and merge this one and then we can create a ticket to fix that one.

**Comment by luisvasq** [comment]
@connor-makowski, looks good to me. I might just fix the issue in https://github.com/MIT-CAVE/cave_static/issues/185 since it's still open.

**Pull request merged**
